using UnityEngine;

namespace Protobot {
    /// <summary>
    /// Attached to every aluminum part generated by AluminumPartGenerator
    /// (C-channels, angles, rails, U-channels) so the Properties Menu can
    /// resize the part at runtime without referencing the original prefab.
    ///
    /// Populated by AluminumPartGenerator.Generate() immediately after the
    /// part GameObject is built.
    /// </summary>
    public class AluminumResizeData : MonoBehaviour {

        [Tooltip("Sub-parts catalog used to build this part's mesh and hole colliders.")]
        public AluminumSubParts subParts;

        [Tooltip("Current hole (segment) count.")]
        public int holeCount;

        [Tooltip("Maximum allowed hole count (from AluminumSubParts).")]
        public int maxHoleCount = 35;

        [Tooltip("Minimum allowed hole count.")]
        public int minHoleCount = 2;

        // ── PartName rebuild data ─────────────────────────────────────────────
        // Used by AluminumResizer to update the part's display name after
        // resizing without having to re-run the full generator.

        [Tooltip("Everything in PartName.name before the hole count. " +
                 "E.g. \"1x2x1 C-Channel (\" for a 1x2 C-Channel.")]
        public string namePrefix;

        [Tooltip("Everything in PartName.name after the hole count. Usually \")\".")]
        public string nameSuffix = ")";

        [Tooltip("PartName.param2Label value (e.g. \"Length\").")]
        public string param2Label;

        [Tooltip("Format string for PartName.param2Display. {0} is replaced with " +
                 "the new hole count. E.g. \"{0} holes\"")]
        public string param2DisplayFormat = "{0} holes";

        [Tooltip("Weight in grams per hole, for PartName.weightInGrams.")]
        public float weightPerHole;
    }
}
