using UnityEngine;

namespace Protobot {
    /// <summary>
    /// Attached to every part generated by <see cref="ChildPartGenerator"/> so the
    /// Properties Menu can offer a size selector (◄ / ►) to swap the part for a
    /// different variant from the same generator (e.g. a different screw length).
    ///
    /// Populated by <see cref="ChildPartGenerator.Generate"/> immediately after the
    /// part GameObject is built.
    /// </summary>
    public class ChildPartResizeData : MonoBehaviour {

        [Tooltip("Generator used to regenerate this part with a different param1 value.")]
        public ChildPartGenerator generator;

        [Tooltip("The param1 value used to generate this part (e.g. \"2.25in\").")]
        public string currentParam1Value;

        [Tooltip("The param2 value used to generate this part (only set for two-param generators, " +
                 "e.g. spacers where param1=Type and param2=Size).")]
        public string currentParam2Value;
    }
}
