using UnityEngine;

namespace Protobot {
    /// <summary>
    /// Attached to every plate generated by PlatePartGenerator so the
    /// Properties Menu can resize the plate at runtime without referencing
    /// the original prefab.
    ///
    /// Populated by PlatePartGenerator.Generate() immediately after the
    /// part GameObject is built.
    ///
    /// Hole-count math reference (same per-axis as AluminumResizer):
    ///   Each hole occupies 0.5 VEX units in both X and Y, so:
    ///     half-extent = holeCount * 0.25
    ///   The mesh is always centred at the GameObject's origin.
    /// </summary>
    public class PlateResizeData : MonoBehaviour {

        [Tooltip("Generator used to rebuild this plate's mesh and hole colliders.")]
        public PlatePartGenerator generator;

        [Tooltip("Current hole count along the local X axis (Length).")]
        public int length;

        [Tooltip("Current hole count along the local Y axis (Width).")]
        public int width;

        [Tooltip("Maximum allowed length.")]
        public int maxLength = 35;

        [Tooltip("Minimum allowed length.")]
        public int minLength = 1;

        [Tooltip("Maximum allowed width.")]
        public int maxWidth = 35;

        [Tooltip("Minimum allowed width.")]
        public int minWidth = 1;

        [Tooltip("Weight in grams per hole (used to compute total weight).")]
        public float weightPerHole = 0.53f;
    }
}
