using UnityEngine;

namespace Protobot {
    /// <summary>
    /// Attached to every shaft generated by ShaftPartGenerator so the
    /// Properties Menu can resize the shaft at runtime without referencing
    /// the original prefab.
    ///
    /// The shaft is scaled along its local Z axis via transform.localScale.z,
    /// so no mesh vertex manipulation is needed — Unity applies the scale
    /// automatically to both the renderer and any mesh colliders.
    ///
    /// Populated by ShaftPartGenerator.Generate() immediately after the
    /// shaft GameObject is built.
    /// </summary>
    public class ShaftResizeData : MonoBehaviour {

        [Tooltip("Current shaft length in inches (matches transform.localScale.z).")]
        public float length;

        [Tooltip("Minimum allowed length in inches.")]
        public float minLength = 0.5f;

        [Tooltip("Maximum allowed length in inches (12 for Normal, 24 for High Strength).")]
        public float maxLength = 12f;

        [Tooltip("Weight in grams per inch of shaft length (1.9 Normal, 6.5 HS).")]
        public float weightPerInch;

        [Tooltip("Suffix appended to the length to form PartName.name. " +
                 "E.g. '\" Shaft' for a normal shaft, '\" HS Shaft' for high strength.")]
        public string nameSuffix;
    }
}
