name: Unity Build

on:
  workflow_dispatch:
    inputs:
      buildTarget:
        description: "Build Target Platform"
        required: true
        default: "StandaloneWindows64"
        type: choice
        options:
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
          - Android
          - iOS
      unityVersion:
        description: "Unity Version"
        required: true
        default: "2021.3.5f1"
        type: string
  pull_request:
    branches:
      - main # Or your main branch name, e.g., develop, master
  push:
    branches:
      - main # Or your main branch name, e.g., develop, master

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        buildTarget:
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ github.sha }}-${{ matrix.buildTarget }}
          restore-keys: |
            Library-${{ github.sha }}-${{ matrix.buildTarget }}
            Library-  # Fallback to a general library cache

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.buildTarget }}
          unityVersion: ${{ github.event.inputs.unityVersion || '2021.3.5f1' }} # Use workflow input or default if not provided.  Important to handle missing input on push/pull_request
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.buildTarget }}
          path: build/${{ matrix.buildTarget }}
