name: Unity Build

on:
  workflow_dispatch:
    inputs:
      buildTarget:
        description: "Build Target Platform"
        required: true
        default: "StandaloneWindows64"
        type: choice
        options:
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
          - Android
          - iOS
      unityVersion:
        description: "Unity Version"
        required: true
        default: "2021.3.5f1"
        type: string

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ github.sha }}
          restore-keys: |
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ github.event.inputs.buildTarget }}
          unityVersion: ${{ github.event.inputs.unityVersion }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ github.event.inputs.buildTarget }}
          path: build/${{ github.event.inputs.buildTarget }}
